Third homework first pull request
Tang-Kai-1/homework pull request #3
Opened 2022-09-19 16:09 UTC by Tang-Kai-1

2022-10-21 18:03 UTC, NilsKula requested changes
:+1:

2022-10-21 18:03 UTC, NilsKula commented on Homework/src/io/codelex/arrays/practice/Exercise8.java
> +    public static void playGame() {
private
metode sanāk visai gara, vajadzetu apsvērt izmantot kādas palīgmetodes

2022-10-21 18:03 UTC, NilsKula commented on Homework/src/io/codelex/arrays/practice/TicTacToe.java
> +        if (board[0][0] == 'X' && board[0][1] == 'X' && board[0][2] == 'X') return true;
```
if() {
foo
} else if() {
bar
} else {
qwe
}

2022-10-21 18:03 UTC, NilsKula commented on Homework/src/io/codelex/arrays/practice/TicTacToe.java
> +        else return countEmpty == 0;
vienkārši return false?

2022-10-21 18:03 UTC, NilsKula commented on Homework/src/io/codelex/classesandobjects/practice/Account.java
> +    public static void transfer(Account from, Account to, double howMuch) {
private

2022-10-21 18:03 UTC, NilsKula commented on Homework/src/io/codelex/classesandobjects/practice/Car.java
> +        return calculateConsumption() > 15;
konstante

2022-10-21 18:03 UTC, NilsKula commented on Homework/src/io/codelex/classesandobjects/practice/Dog.java
> +    private String nameFather="Unknown";
formatting, bišķi vairāk space jāizmanto :smile:

2022-10-21 18:03 UTC, NilsKula commented on Homework/src/io/codelex/classesandobjects/practice/videostore/Video.java
> +    protected boolean isCheckedOut() {
var neizmantot `protected`
`protected boolean isCheckedOut()` ir taspats kas `boolean isCheckedOut()`

2022-10-22 13:17 UTC, Tang-Kai-1 commented on Homework/src/io/codelex/arrays/practice/TicTacToe.java
> +        else return countEmpty == 0;
Neredzu īsti iemeslu pēc tā, jo ar return countEmpty == 0 jau tā atgriezīs false ja neizpildās neviena no kombinācijām, bet vēl ir brīvi lauciņi un true gadījumā ja visi ir aizpildīti.

2022-10-27 13:38 UTC, NilsKula commented on Homework/src/io/codelex/arrays/practice/TicTacToe.java
> +        else return countEmpty == 0;
`countEmpty == 0` vienmēr būs false
tādēļ 
`return false` būs noteikti sparotamāk nekā `return countEmpty == 0`

2022-10-27 13:38 UTC, NilsKula approved these changes

2022-11-19 23:20 UTC, merged